// Code generated by Kitex v0.4.4. DO NOT EDIT.
package account

import (
	server "github.com/cloudwego/kitex/server"
	account "github.com/rdstihz/SimpleAccountBook/kitex_gen/account"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler account.Account, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
